#!/bin/bash

# Modified from:
# https://hub.docker.com/_/postgres/
set -e

echo $POSTGRES_USER
echo $POSTGRES_DB

psql -v ON_ERROR_STOP=1 -v VERBOSITY=verbose --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE pm_test;
  \c pm_test

  GRANT ALL PRIVILEGES ON DATABASE pm_test TO pm;
  ALTER DEFAULT PRIVILEGES FOR ROLE pm IN SCHEMA PUBLIC GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pm;
  ALTER DEFAULT PRIVILEGES FOR ROLE pm IN SCHEMA PUBLIC GRANT EXECUTE ON FUNCTIONS TO pm;
EOSQL
